apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcserver-app
spec:
  selector:
    matchLabels:
      name: grpcserver-app
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: grpcserver-app
    spec:
      containers:
        - name: container
          image: grpc-server
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
            - containerPort: 6565
      terminationGracePeriodSeconds: 10
