apiVersion: v1
kind: Service
metadata:
  name: grpcserver-svc
spec:
  selector:
    name: grpcserver-app
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: grpc
      port: 6565
      protocol: TCP
      targetPort: 6565
  type: NodePort
