apiVersion: apps/v1
kind: Deployment
metadata:
  name: be03-app
spec:
  selector:
    matchLabels:
      name: be03-app
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: be03-app
    spec:
      containers:
        - name: container
          image: be03
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: "JAVA_OPTS"
              value: "-Dredis.host=redis-master -Dspring.profiles.active=dev"
      terminationGracePeriodSeconds: 10
