grpc:
  port: 6565
eureka:
  host: localhost
  port: 8761
  instance:
    metadata-map:
      grpc-port: ${grpc.port}
  client:
    service-url:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
spring:
  application:
    name: grpc-server
server:
  port: 8080
