apiVersion: apps/v1
kind: Deployment
metadata:
  name: be02-app
spec:
  selector:
    matchLabels:
      name: be02-app
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: be02-app
    spec:
      containers:
        - name: container
          image: localhost:5000/be02:latest
          ports:
            - containerPort: 8080
      terminationGracePeriodSeconds: 10
