spring:
  application:
    name: grpc-client
server:
  port: 8080
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
grpc:
  eureka:
    service-id: GRPC-SERVER
eureka:
  host: localhost
  port: 8761

  instance:
    metadata-map:
      grpcport: ${grpc.port}
  client:
    service-url:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
    enabled: true
    register-with-eureka: false